Helperland/Helperland/Controllers/AdminController.cs
using Helperland.Helpers;
using Helperland.Models.ViewModel.Admin;
using Helperland.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Helperland.Controllers
{
    [SessionHelper(UserTypeID: 3)]
    public class AdminController : Controller
    {
        private readonly IUserRegistrationRepository userRegistrationRepository;
        private readonly IServiceRequestRepository serviceRequestRepository;
        private readonly IBookServiceRepository bookServiceRepository;

        public AdminController(IUserRegistrationRepository userRegistrationRepository,IServiceRequestRepository serviceRequestRepository
                               ,IBookServiceRepository bookServiceRepository)
        {
            this.userRegistrationRepository = userRegistrationRepository;
            this.serviceRequestRepository = serviceRequestRepository;
            this.bookServiceRepository = bookServiceRepository;
        }
        [HttpPost]
        public IActionResult Index(ServiceHistoryAdminViewModel serchData)
        {
            ViewBag.city = bookServiceRepository.GetAllCity().Select(x => new SelectListItem()
            {
                Text = x.CityName,
                Value = x.Id.ToString()
            });
            ServiceHistoryAdminViewModel model = new ServiceHistoryAdminViewModel();
            model.ServiceHistory = serviceRequestRepository.GetServiceBySearch(serchData);
            return View(model);
        }

        public IActionResult Index()
        {
            ViewBag.city = bookServiceRepository.GetAllCity().Select(x => new SelectListItem()
            {
                Text = x.CityName,
                Value = x.Id.ToString()
            });
            ServiceHistoryAdminViewModel model = new ServiceHistoryAdminViewModel();
            model.ServiceHistory = serviceRequestRepository.GetAllServiceListForAdmin();
            return View(model);
        }
        public IActionResult UserManagement()
        {
            ServiceHistoryAdminViewModel model = new ServiceHistoryAdminViewModel();
            model.UserList = userRegistrationRepository.GetAllUser();
            return View(model);
        }
        [HttpPost]
        public IActionResult UserManagement(ServiceHistoryAdminViewModel serchData)
        {
            ServiceHistoryAdminViewModel model = new ServiceHistoryAdminViewModel();
            model.UserList = userRegistrationRepository.GetFilterUserList(serchData.UserSearchModel);
            return View(model);
        }

        public bool DeleteUser(string userId)
        {
            return userRegistrationRepository.DeleteUser(Int32.Parse(userId));
        }
        public bool ActivateUser(string userId)
        {
            return userRegistrationRepository.ActivateUser(Int32.Parse(userId));
        }
        public bool DeactivateUser(string userId)
        {
            return userRegistrationRepository.DeactivateUser(Int32.Parse(userId));
        }
        public IActionResult GetServiceRequestData(string ServiceReqestId)
        {

            return Json(JsonConvert.SerializeObject(serviceRequestRepository.GetServiceDetails(Int32.Parse(ServiceReqestId))));
        }
        public IActionResult GetServiceRequestDetailsForEdit(string ServiceReqestId)
        {

            return Json(JsonConvert.SerializeObject(serviceRequestRepository.GetServiceDetailsForAdmin(Int32.Parse(ServiceReqestId))));
        }

        public IActionResult EditService(ServiceHistoryAdminViewModel editData)
        {
            if (ModelState.IsValid)
            {
                serviceRequestRepository.UpdateServiceRequest(editData.EditServiceModel);
            }
       
            ViewBag.city = bookServiceRepository.GetAllCity().Select(x => new SelectListItem()
            {
                Text = x.CityName,
                Value = x.Id.ToString()
            });
            return RedirectToAction("Index");

        }

        public bool ApproveServiceProvider(string userId)
        {
            return userRegistrationRepository.ApproveServiceProvider(Int32.Parse(userId));
        }
        public bool DisApproveServiceProvider(string userId)
        {
            return userRegistrationRepository.DisApproveServiceProvider(Int32.Parse(userId));
        }

        public IActionResult GetRefundDetails(string serviceRequestId)
        {
            return Json(JsonConvert.SerializeObject(serviceRequestRepository.GetRefundDetails(Int32.Parse(serviceRequestId))));
        }

        public IActionResult RefundAmount(ServiceHistoryAdminViewModel refund)
        {

            serviceRequestRepository.RefundAmount(refund.RefundModel);
           return RedirectToAction("Index");
        }
    }
}

Helperland/Helperland/Controllers/BookServiceController.cs
using Helperland.Helpers;
using Helperland.Models.Data;
using Helperland.Models.ViewModel.BookService;
using Helperland.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Helperland.Controllers
{
    [SessionHelper(UserTypeID:1)]
    public class BookServiceController : Controller
    {
        private readonly IBookServiceRepository bookServiceRepository;
        private readonly IAddressRepository addressRepository;
        public BookServiceController(IBookServiceRepository bookServiceRepository, IAddressRepository addressRepository)
        {
            this.bookServiceRepository = bookServiceRepository;
            this.addressRepository = addressRepository;
        }
        public IActionResult Index()
        {

            ViewBag.city= bookServiceRepository.GetAllCity().Select(x => new SelectListItem()
            {
                Text = x.CityName,
                Value = x.Id.ToString()
            });
           
            return View();
        }
        [HttpPost]
        public JsonResult CheckPincode(string Pincode)
        {
            if(Pincode.Length > 7 || ! Regex.IsMatch(Pincode, @"^[0-9]{6}$"))
            {
                return Json( false);
            }
            else
            {
                if (bookServiceRepository.CheckAvailabilityOfService(Pincode))
                {
                    return Json(true);
                }
                else
                    return Json("We are not providing service in this area. We’ll notify you if any helper would start working near your area.");
            }
        }

        [HttpPost]
        public IActionResult AddAddress([FromBody] AddressViewModel address)
        {
            if(address.UserId != null && address.AddressLine1 != null && address.AddressLine2 != null && address.CityId != null)
            {
                if (addressRepository.SetAddress(address))
                {
                    return Json(true);
                }
                else
                {
                    return Json(false);
                }
            }
            else
            {
                return Json(false);
            }
           
        }
        public IActionResult GetAddress(string userID)
        {
            List<AddressViewModel> addresses = addressRepository.GetAddress(Int32.Parse(userID));
            if (addresses == null)
            {
                Json(false);
            }
               return Json( JsonConvert.SerializeObject(addresses));
            
        }

        [HttpPost]
        public IActionResult BookServiceRequest(BookServiceViewModel bookServiceViewModel)
        {
            ViewBag.ServiceRequestID = bookServiceRepository.BookService(bookServiceViewModel);
            ViewBag.SuccessRequest = true;
            ViewBag.city = bookServiceRepository.GetAllCity().Select(x => new SelectListItem()
            {
                Text = x.CityName,
                Value = x.Id.ToString()
            });
            return View("Index");
        }

    }
}

Helperland/Helperland/Controllers/CustomerController.cs
using Helperland.Helpers;
using Helperland.Models.Data;
using Helperland.Models.ViewModel.BookService;
using Helperland.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace Helperland.Controllers
{
    [SessionHelper(UserTypeID: 1)]
    public class CustomerController : Controller
    {
        private readonly IAddressRepository addressRepository;
        private readonly IBookServiceRepository bookServiceRepository;
        private readonly IUserRegistrationRepository userRegistrationRepository;
        private readonly IServiceRequestRepository serviceRequestRepository;
        private readonly IRatingRepository ratingRepository;
        private readonly ILoginRepository loginRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private ISession _session => _httpContextAccessor.HttpContext.Session;
        public CustomerController(IAddressRepository addressRepository,IBookServiceRepository bookServiceRepository,
                                  IUserRegistrationRepository userRegistrationRepository,IServiceRequestRepository serviceRequestRepository,
                                  IRatingRepository ratingRepository,ILoginRepository loginRepository,
                                  IHttpContextAccessor httpContextAccessor)
        {
            this.bookServiceRepository = bookServiceRepository;
            this.addressRepository = addressRepository;
            this.userRegistrationRepository = userRegistrationRepository;
            this.serviceRequestRepository = serviceRequestRepository;
            this.ratingRepository = ratingRepository;
            this.loginRepository = loginRepository;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            int userId=(int) _session.GetInt32("userID");
            return View(serviceRequestRepository.GetServicesByUserId(userId) );
        }

        public IActionResult Dashbord()
        {
            ViewBag.city = bookServiceRepository.GetAllCity().Select(x => new SelectListItem()
            {
                Text = x.CityName,
                Value = x.Id.ToString()
            });
            return View();
        }

        public IActionResult GetAddress(string userID)
        {
            List<AddressViewModel> addresses = addressRepository.GetAddress(Int32.Parse(userID));
            if (addresses == null)
            {
                Json(false);
            }
            return Json(JsonConvert.SerializeObject(addresses));

        }
        public IActionResult GetAddressById(string AddressID)
        {
            AddressViewModel addresses = addressRepository.GetAddressById(Int32.Parse(AddressID));
            if (addresses == null)
            {
                Json(false);
            }
            return Json(JsonConvert.SerializeObject(addresses));

        }
        [HttpPost]
        public IActionResult UpdateAddress([FromBody] AddressViewModel address)
        {
            if (addressRepository.UpdateAddress(address))
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }

        }

        [HttpPost]
        public IActionResult AddNewAddress([FromBody] AddressViewModel address)
        {
            if (addressRepository.SetAddress(address))
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }

        }
        [HttpPost]
        public IActionResult DeleteAddress(string AddressId)
        {
            if (addressRepository.DeleteAddress(Int32.Parse(AddressId)))
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }

        }

        public IActionResult GetUserById(string userId)
        {
            User user;
            user = userRegistrationRepository.GetUserById(Int32.Parse(userId));
            if (user == null)
            {
                Json(false);
            }
            int lan = 0;
            if (user.LanguageId != null)
            {
                lan = (int)user.LanguageId;
            }
            var u = new
            {
                userId = user.UserId,
                firstName=user.FirstName,
                lastName=user.LastName,
                month = Convert.ToDateTime(user.DateOfBirth).Month,
                day = Convert.ToDateTime(user.DateOfBirth).Day,
                year = Convert.ToDateTime(user.DateOfBirth).Year,
                email = user.Email,
                mobileNumber = user.Mobile,
                language = lan
            };
            return Json(JsonConvert.SerializeObject(u));
        }

        [HttpPost]
        public IActionResult UpdateUserData(string FirstName,string LastName,string DOB,string MobileNumber, string UserId, string LanguageId)
        {
            var i = userRegistrationRepository.ChangeUserData(FirstName, LastName, DOB, MobileNumber, Int32.Parse(UserId), Int32.Parse(LanguageId));
            return Json(i);
        }

        public IActionResult GetServiceRequestData(string ServiceReqestId)
        {
            
            return Json(JsonConvert.SerializeObject(serviceRequestRepository.GetServiceDetails(Int32.Parse(ServiceReqestId))));
        }

        public string GetServiceDate(string serviceReqestId)
        {

            return serviceRequestRepository.GetServiceDate(Int32.Parse(serviceReqestId));
        }

        public bool UpdateServiceDate(string serviceDate,string serviceProviderId)
        {
            return serviceRequestRepository.UpdateServiceDate(Int32.Parse(serviceProviderId),Convert.ToDateTime(serviceDate));
        }
        public bool CancelService(string serviceRequestId, string message)
        {
            return serviceRequestRepository.CancelService(Int32.Parse(serviceRequestId),message);
        }

        public IActionResult ServiceHistory()
        {
            int userId = (int)_session.GetInt32("userID");
            return View(serviceRequestRepository.GetServicesHistoryByUserId(userId));
        }

        public bool AddRating(string ServiceReqestId, string onTime, string friendly, string qualityOfService,string feedBack)
        {
            return ratingRepository.AddRating(Int32.Parse(ServiceReqestId), decimal.Parse(onTime), decimal.Parse(friendly), decimal.Parse(qualityOfService), feedBack);
        }

        public bool ResetPassword(string oldPassword, string newPassword)
        {
            int userId= (int)_session.GetInt32("userID");
            
            return loginRepository.ResetPassword(userId, oldPassword, newPassword);
        }
    }
}

Helperland/Helperland/Views/Shared/_CustomerSidetaMenuPartialView.cshtml
<div class="col-md-2 service-menu g-0">
    <div class="side-menu-item">
        <a asp-action="Index" asp-controller="Customer" class="nav-link">Dashboard </a>  
    </div>
    <div class="side-menu-item">
        <a asp-action="ServiceHistory" asp-controller="Customer" class="nav-link"> Service History </a>
       
    </div>
    <div class="side-menu-item ">
        <a asp-action="" asp-controller="" class="nav-link">Service Schedule </a>
        
    </div>
    <div class="side-menu-item">
        <a asp-action="" asp-controller="" class="nav-link">Favourite Pros </a>
        
    </div>
    <div class="side-menu-item">
        <a asp-action="" asp-controller="" class="nav-link">Invoice </a>
        
    </div>
    <div class="side-menu-item">
        <a asp-action="" asp-controller="" class="nav-link">Notification </a>
        
    </div>
</div>

Helperland/Helperland/Views/Shared/_ForgetPasswordView.cshtml
@model Helperland.Models.ViewModel.ForgetPasswordLoginModel
<div class="modal fade" id="ForgetPasswordModel" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Forgot password</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="alert alert-success alert-dismissible fade show " id="Forget-alert-success" style="display:none" role="alert">
                          Mail sent to your Email Address.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                <div class="alert alert-danger alert-dismissible fade show " id="Forget-alert" style="display:none" role="alert">
                    <div asp-validation-summary="ModelOnly"></div>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                <form asp-action="ForgrtPassword" asp-controller="home" id="ForgetPasswordforrm">
                    <input asp-for="Email" placeholder="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                    <input type="submit" class="btn rounded-pill marun font-white d-block form-control mt-3" />
                </form>
            </div>
            <div class="modal-footer justify-content-center">
                <a class="" data-bs-target="#LoginModel" data-bs-toggle="modal" data-bs-dismiss="modal">Login now</a>
            </div>
        </div>
    </div>
</div>

Helperland/Helperland/Views/Shared/_HomeLayout.cshtml
@model Helperland.Models.ViewModel.LoginViewModel;
@using Microsoft.AspNetCore.Http
@{ int? userID = Context.Session.GetInt32("userID"); }
@{ int? Usertype = Context.Session.GetInt32("usertype"); }
<!DOCTYPE html>
<html>

<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="keywords">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
    <!--  Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet" />

</head>

<body id="body">
    <div class="loder-wrapper">
        <div class="loader"></div>
    </div>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-xl navbar-light home-navbar" id="nav">
        <div class="container-fluid">
            <a class="navbar-brand" asp-action="index" asp-controller="home">
                <img src="~/image/white-logo-transparent-background.png" asp-append-version="true" id="brand-logo" />
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0" id="navLinks">


                    @if (userID == null)
                    {
                        <li class="nav-item hover-blue">
                            <a class="nav-link rounded-link" asp-action="index" asp-controller="BookService">Book a Cleaner</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="prices" asp-controller="home">Prices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Our Guarantee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="contact" asp-controller="home">Contact us</a>
                        </li>
                        <li class="nav-item hover-blue">
                            <a class="nav-link rounded-link" data-bs-toggle="modal" data-bs-target="#LoginModel">Login</a>
                        </li>
                        <li class="nav-item hover-blue">
                            <a class="nav-link rounded-link" asp-action="ServiceProviderSignUP" asp-controller="home">Become a Helper</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="~/image/gb.svg" asp-append-version="true" alt="united kingdom flag"
                                     class="county-flag">
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <img src="~/image/in.svg" asp-append-version="true" alt="united kingdom flag"
                                             class="county-flag">
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <img src="~/image/us.svg" asp-append-version="true" alt="united kingdom flag"
                                             class="county-flag">
                                    </a>
                                </li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        if (Usertype == 1)
                        {
                            <li class="nav-item diaplay-center">
                                <a class="nav-link rounded-link active" asp-action="index" asp-controller="BookService">Book now </a>
                            </li>
                        }

                        <li class="nav-item diaplay-center">
                            <a class="nav-link " asp-action="prices" asp-controller="Home">Prices & services</a>
                        </li>
                        <li class="nav-item diaplay-center">
                            <a class="nav-link" href="#">Warranty </a>
                        </li>
                        <li class="nav-item diaplay-center">
                            <a class="nav-link" href="#">Blog</a>
                        </li>
                        <li class="nav-item diaplay-center">
                            <a class="nav-link" asp-action="Contact" asp-controller="home"> Contact</a>
                        </li>
                        <li class="nav-item display-non-sm diaplay-center">
                            <img src="~/image/icon-notification.png" class=" nav-border nav-link-image">
                        </li>
                        <li class="nav-item dropdown display-non-sm">
                            <a class="nav-link dropdown-toggle diaplay-center" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="~/image/user.png" id="navbar-user-image"
                                     class="county-flag nav-link-image-user">
                            </a>
                            <ul class="dropdown-menu dropdown-set-width" aria-labelledby="navbarDropdown">
                                <li class="">
                                    <a class="dropdown-item nav-dropdown-item" href="#">
                                        <small>Welcome,</small>
                                        @Context.Session.GetString("username")
                                    </a>
                                    <hr>
                                </li>

                                @if (Usertype == 1)
                                {
                                    <li class="">
                                        <a class="dropdown-item nav-dropdown-item" asp-action="Index" asp-controller="Customer">
                                            My Dashboard
                                        </a>
                                    </li>
                                    <li class="">
                                        <a class="dropdown-item nav-dropdown-item" asp-action="Dashbord" asp-controller="Customer">
                                            My Setting
                                        </a>
                                    </li>

                                }
                                else if (Usertype == 2)
                                {
                                    <li class="">
                                        <a class="dropdown-item nav-dropdown-item" asp-action="Index" asp-controller="ServiceProvider">
                                            My Dashboard
                                        </a>
                                    </li>
                                    <li class="">
                                        <a class="dropdown-item nav-dropdown-item" asp-action="MySetting" asp-controller="ServiceProvider">
                                            My Setting
                                        </a>
                                    </li>
                                }
                                <li class="">
                                    <a class="dropdown-item nav-dropdown-item" asp-action="Logout" asp-controller="Home">
                                        Logout
                                    </a>
                                </li>

                            </ul>
                        </li>
                    }



                </ul>
            </div>
        </div>
    </nav>

    @if (userID == null)
    {
        <partial name="_LoginPartialView" model="Model" />
    }

    @RenderBody()

    <section id="newslatter">
        <div class="container">
            <div class="row">
                <div class="col-md-1 ">
                    <a href="#home" class="link"> <i class="bi bi-arrow-up-circle newslatter-size"></i> </a>
                </div>
                <div class="col-md-6 offset-md-2">
                    <h2>
                        Get Our Newsletter
                    </h2>
                    <input type="email" placeholder="Your Email">
                    <button class="btn btn-sm">Submit</button>
                </div>
                <div class="col-md-1 offset-md-2 text-right ">
                    <img class="img-fluid" src="~/image/layer-598.png" asp-append-version="true">
                </div>
            </div>
        </div>
    </section>


    <footer>

        <div class="container-fluid">
            <div class="row footer-main justify-content-center">
                <div class="col-md-2 col-sm-12 text-center">
                    <img src="~/image/white-logo-transparent-background.png" asp-append-version="true"
                         class="img-fluid">
                </div>
                <div class="col-md-8 col-sm-12">
                    <ul>
                        <li> <a asp-action="index" asp-controller="home" class="link">Home</a> </li>
                        <li> <a asp-action="about" asp-controller="home" class="link">About</a>  </li>
                        <li> <a href="#" class="link">TestiMonials </a>  </li>
                        <li><a asp-action="faq" asp-controller="home" class="link">Faq</a>  </li>
                        <li><a href="#" class="link">Insurance Policy</a>  </li>
                        <li><a href="#" class="link">Impressun</a>  </li>
                    </ul>

                </div>
                <div class="col-md-1 col-sm-12 text-center">
                    <i class="bi bi-facebook"></i>
                    <i class="bi bi-instagram"></i>
                </div>
            </div>
        </div>

        <div class="footer-line"></div>
        <div class="footer-last-row">
            Lorem ipsum dolor, sit amet consectetur  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Esse modi, repudiandae deserunt . <span> </span>
            <input type="button" class="btn btn-sm btn-warning" onclick="closeDiv()" id="warningbtn" value="ok">
        </div>
    </footer>



    <!-- Jquery -->
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>



    @if (ViewBag.isLoginOpen == true)
    {
        <script>
            $(window).on('load', function () {
                $('#LoginModel').modal('show');
            });
        </script>

    }
    @if (ViewBag.isOpen == true)
    {
        <script>
            $(window).on('load', function () {
                $('#LoginModel').modal('show');
                $('#login-alert').show();
            });
        </script>

    }
    @if (ViewBag.isForgetPasswordOpen == true)
    {
        <script>
            $(window).on('load', function () {
                $('#ForgetPasswordModel').modal('show');
                $('#Forget-alert').show();
            });
        </script>
    }
    @if (ViewBag.sendMail == true)
    {
        <script>
            $(window).on('load', function () {
                $('#ForgetPasswordModel').modal('show');
                $('#Forget-alert-success').show();
                $('#ForgetPasswordforrm').hide();
            });
        </script>
    }
    <!-- Main Js File-->
    <script src="~/js/main.js"></script>
    @RenderSection("Script", required: false);


    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/ae6d6e0254.js" crossorigin="anonymous"></script>
</body>

</html>