Helperland/Helperland/Models/ViewModel/Customer/ServiceHistoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Helperland.Models.ViewModel.Customer
{
    public class ServiceHistoryViewModel
    {
        public int ServiceId { get; set; }
        public String StartDate { get; set; }
        public int? ServiceProvideId { get; set; }
        public string ServiceProviderName { get; set; }
        public decimal Payment { get; set; }
        public int? Status { get; set; }
        public bool Rate { get; set; }
        public decimal? Rating { get; set; }
        public string Avatar { get; set; }
    }
}

Helperland/Helperland/Models/ViewModel/ServiceProvider/BlockCustomerrViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Helperland.Models.ViewModel.ServiceProvider
{
    public class BlockCustomerrViewModel
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public bool IsBlock { get; set; }

    }
}

Helperland/Helperland/Models/ViewModel/ServiceProvider/MyDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Helperland.Models.ViewModel.ServiceProvider
{
    public class MyDetailsViewModel
    {
        [Required (ErrorMessage ="Please Enter First name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please Enter Last name")]
        public string lastName { get; set; }
        [Required(ErrorMessage = "Please Enter month ")]
        public int month { get; set; }
        [Required(ErrorMessage = "Please Enter Day ")]
        public int day { get; set; }
        [Required(ErrorMessage = "Please Enter Year")]
        public int year { get; set; }
        public string email { get; set; }
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "enter valid phone number")]
        [Required(ErrorMessage = "Please Enter Mobile Number")]
        public string mobileNumber { get; set; }

        [Required(ErrorMessage = "Please select Gender")]
        public int Gender { get; set; }

        [Required(ErrorMessage = "Please select Avatar")]
        public string UserProfilePicture { get; set; }
        [Required(ErrorMessage = "Please select Nationality")]
        public int NationalityId { get; set; }

        public bool IsActive { get; set; }
        [Required(ErrorMessage = "Please enter street no")]
        public string AddressLine1 { get; set; }
        [Required(ErrorMessage = "Please enter  house number")]
        public string AddressLine2 { get; set; }
        [Required(ErrorMessage = "Please enter zipcode")]
        public string Zipcode { get; set; }
        public int CityId { get; set; }




    }
}

Helperland/Helperland/Models/ViewModel/ServiceProvider/NewServiceRequestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Helperland.Models.ViewModel.ServiceProvider
{
    public class NewServiceRequestViewModel
    {
        public int ServiceRequestID { get; set; }
        public string  ServicestarDate { get; set; }
        public string  CustomerName { get; set; }
        public string Addressline1 { get; set; }
        public string Addressline2 { get; set; }
        public decimal  Payment { get; set; }

    }
}

Helperland/Helperland/Models/ViewModel/ServiceProvider/RatingsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Helperland.Models.ViewModel.ServiceProvider
{
    public class RatingsViewModel
    {
        public int RatingID { get; set; }
        public string CustomerName { get; set; }
        public int ServiceRequestID { get; set; }
        public string Comments { get; set; }
        public string ServiceDate { get; set; }
        public decimal Rating { get; set; }
    }
}

Helperland/Helperland/Models/ViewModel/ServiceProvider/ServiceProviderServiceHistoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Helperland.Models.ViewModel.ServiceProvider
{
    public class ServiceProviderServiceHistoryViewModel
    {
        public int ServiceRequestId { get; set; }
        public string CustomerName { get; set; }
        public string ServiceDate { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }

    }
}

Helperland/Helperland/Controllers/ServiceProviderController.cs
using Helperland.Helpers;
using Helperland.Models.Data;
using Helperland.Models.ViewModel.ServiceProvider;
using Helperland.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Helperland.Controllers
{
    [SessionHelper(UserTypeID: 2)]
    public class ServiceProviderController : Controller
    {
        private readonly IUserRegistrationRepository userRegistrationRepository;
        private readonly IAddressRepository addressRepository;
        private readonly IBookServiceRepository bookServiceRepository;
        private readonly ILoginRepository loginRepository;
        private readonly IRatingRepository ratingRepository;
        private readonly IServiceRequestRepository serviceRequestRepository;
        private readonly IFavouriteAndBlockRepository favouriteAndBlockRepository;
        private readonly IHttpContextAccessor httpContextAccessor;

        private ISession _session => httpContextAccessor.HttpContext.Session;

        public ServiceProviderController(IUserRegistrationRepository userRegistrationRepository, IAddressRepository addressRepository,
                                IBookServiceRepository bookServiceRepository,ILoginRepository loginRepository,
                                IRatingRepository ratingRepository,IServiceRequestRepository serviceRequestRepository,
                                IFavouriteAndBlockRepository favouriteAndBlockRepository, IHttpContextAccessor httpContextAccessor)
        {
            this.userRegistrationRepository = userRegistrationRepository;
            this.addressRepository = addressRepository;
            this.bookServiceRepository = bookServiceRepository;
            this.loginRepository = loginRepository;
            this.ratingRepository = ratingRepository;
            this.serviceRequestRepository = serviceRequestRepository;
            this.favouriteAndBlockRepository = favouriteAndBlockRepository;
            this.httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult NewServiceRquest(string hasPate)
        {
            int userId = (int)_session.GetInt32("userID");
            bool hasPasts ;
            if (hasPate == "on")
            {
                hasPasts = true;
            }
            else
            {
                hasPasts = false;
            }
            ViewBag.hasPat = hasPasts;
            return View(serviceRequestRepository.GetServiceRequestsNotAccepted(userId, hasPasts));
        }
        public IActionResult UpcomingServices()
        {
            int userId = (int)_session.GetInt32("userID");
            return View(serviceRequestRepository.GetServiceRequestsIsAccepted(userId));
        }
        public IActionResult ServiceHistory()
        {
            int userId = (int)_session.GetInt32("userID");

            return View(serviceRequestRepository.GetServiceHistoryForServiceProvider(userId));
        }
        public IActionResult MyRating(string Rating=null)
        {
            if(Rating == null || Int32.Parse(Rating)==0)
            {
                int userId = (int)_session.GetInt32("userID");
                ViewBag.selectRating = 0;
                return View(ratingRepository.GetRatingsForServiceProvider(userId));
                
            }
            else
            {
                int userId = (int)_session.GetInt32("userID");
                List<RatingsViewModel> temp = ratingRepository.GetRatingsForServiceProvider(userId);
                temp = temp.Where(x => x.Rating > Int32.Parse(Rating) -1 && x.Rating <= Int32.Parse(Rating)).ToList();
                ViewBag.selectRating = Int32.Parse(Rating);
                return View(temp);
            }
           
           
        }

        public IActionResult ServiceSchedule()
        {
            
           return View();
        }

        public IActionResult GetUpcomingServiceRequest()
        {
            int userId = (int)_session.GetInt32("userID");
            return new JsonResult(serviceRequestRepository.GetDateOfAcceptedAndUpcomingServiceRequest(userId));
        }
        public IActionResult BlockCustomer()
        {
            int userId = (int)_session.GetInt32("userID");
            return View(favouriteAndBlockRepository.GetListOfCustomer(userId));
        }
        public IActionResult MySetting()
        {
            int userId = (int)_session.GetInt32("userID");
            MyDetailsViewModel model = new MyDetailsViewModel();
            User user;
            user = userRegistrationRepository.GetUserById(userId);
            UserAddress userAddress = addressRepository.GetServiceProviderAddress(userId);
            if (user != null)
            {
                model.FirstName = user.FirstName;
                model.lastName = user.LastName;
                model.month = Convert.ToDateTime(user.DateOfBirth).Month;
                model.day = Convert.ToDateTime(user.DateOfBirth).Day;
                model.year = Convert.ToDateTime(user.DateOfBirth).Year;
                model.mobileNumber = user.Mobile;
                model.email = user.Email;
                if (user.Gender != null)
                    model.Gender = (int)user.Gender;
                if (user.NationalityId != null)
                    model.NationalityId = (int)user.NationalityId;

                model.UserProfilePicture = user.UserProfilePicture;
                if (user.IsActive != null)
                    model.IsActive = (bool)user.IsActive;
                else
                    model.IsActive = false;

            }
            if (userAddress != null)
            {
                model.AddressLine1 = userAddress.AddressLine1;
                model.AddressLine2 = userAddress.AddressLine2;
                model.Zipcode = userAddress.ZipCode;
                model.CityId = userAddress.CityId;
            }

            ViewBag.city = bookServiceRepository.GetAllCity().Select(x => new SelectListItem()
            {
                Text = x.CityName,
                Value = x.Id.ToString()
            });
            return View(model);
        }

        [HttpPost]
        public IActionResult GetUserData(MyDetailsViewModel myDetailsViewModel)
        {
            int userId = (int)_session.GetInt32("userID");
            if (ModelState.IsValid)
            {
                userRegistrationRepository.UpdateServiceProviderData(myDetailsViewModel, userId);
                
            }
            return RedirectToAction("MySetting");
        }

        public bool ResetPassword(string oldPassword,string newPassword)
        {
            int userId = (int)_session.GetInt32("userID");
            return loginRepository.ResetPassword(userId, oldPassword, newPassword);
        }

        public IActionResult GetServiceRequestData(string ServiceReqestId)
        {
            return Json(JsonConvert.SerializeObject(serviceRequestRepository.GetServiceDetailsforServiceProvider(Int32.Parse(ServiceReqestId))));
        }

        public string AcceptServiceRequest(string serviceRequeestId)
        {
            int userId = (int)_session.GetInt32("userID");
            return serviceRequestRepository.AcceptServiceRequest(userId, Int32.Parse(serviceRequeestId));
        }

        public bool CompleteServiceRequest(string serviceRequeestId)
        {
            return serviceRequestRepository.CompletedService(Int32.Parse(serviceRequeestId));
        }
        public bool CanceledServiceRequest(string serviceRequeestId,string message)
        {
            return serviceRequestRepository.CancelServiceRequest(Int32.Parse(serviceRequeestId), message);
        }

        public bool SetUnblockCustomer(string userId)
        {
            int LoginUserId = (int)_session.GetInt32("userID");
            return favouriteAndBlockRepository.UnblockCustomer(LoginUserId, Int32.Parse(userId));
        }
        public bool SetBlockCustomer(string userId)
        {
            int LoginUserId = (int)_session.GetInt32("userID");
            return favouriteAndBlockRepository.BlockCustomer(LoginUserId, Int32.Parse(userId));
        }

    }
}

Helperland/Helperland/Views/ServiceProvider/Index.cshtml
@{
    Layout = "_Layout";
    ViewBag.Title = "Dashbord";
}
@using Microsoft.AspNetCore.Http
<div class="container-fluid">
    <div class="row justify-content-center gray-bachgroud" style="margin-top: 100px; padding-top: 2rem; padding-bottom: 2rem;">
        <h1 class="text-center"> Welcome, @Context.Session.GetString("username") </h1>
    </div>
    <div class="row justify-content-center mt-2">
        <div class="col-md-2">
            <partial name="_ServiceProviderMenuPartialView" />
        </div>
        <div class="col-md-9">

        </div>
    </div>
</div>
@section Script{
    <style>
        a:hover {
            color: white !important;
        }
    </style>
}

Helperland/Helperland/Views/ServiceProvider/MyRating.cshtml
@{
    Layout = "_Layout";
    ViewBag.Title = "My Rating ";
}
@using Microsoft.AspNetCore.Http
@model List<Helperland.Models.ViewModel.ServiceProvider.RatingsViewModel>
<div class="container-fluid">
    <div class="row justify-content-center gray-bachgroud" style="margin-top: 100px; padding-top: 2rem; padding-bottom: 2rem;">
        <h1 class="text-center"> Welcome, @Context.Session.GetString("username") </h1>
    </div>
    <div class="row justify-content-center mt-2">
        <div class="col-md-2">
            <partial name="_ServiceProviderMenuPartialView" />
        </div>
        <div class="col-md-9 p-3">

            <div class="row m-2">

                <div class="col-md-2">
                    <span class="font-bold">Rating </span>
                </div>
                <div class="col-md-3">
                    <form asp-action="MyRating" asp-controller="ServiceProvider" id="Form-submit">
                        <select class="form-control form-select" name="Rating" id="selectRating">
                            <option value="0">All</option>
                            <option value="5">Excellent</option>
                            <option value="4">Very Good</option>
                            <option value="3">Good</option>
                            <option value="2">Poor</option>
                        </select>
                    </form>
                </div>
            </div>
            <div class="row m-2">
                <div class="col-md-12 table-responsive">
                    <table class="table" id="tbleMyRating">
                        <thead>
                            <tr class="m-2">
                            </tr>
                        </thead>
                        <tbody>


                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <div class="row p-2 mb-3" style="border:1px solid grey">
                                            <div class="col-md-3 mb-2">
                                                <span class="font-bold">@item.ServiceRequestID </span> <br />
                                                <span class="font-bold"> @item.CustomerName </span>
                                            </div>
                                            <div class="col-md-6 mb-2">
                                                <div><img src="/image/calendar2.png"><b>@item.ServiceDate</b> </div>
                                                <div><img src="/image/layer-14.png"> 12:00 - 18:00 </div>
                                            </div>
                                            <div class="col-md-3 mb-2">
                                                <span class="font-bold">Ratings </span><br />
                                                <div>
                                                    @for (var i = 1; i < 6; i++)
                                                    {
                                                        var temp = Convert.ToInt32(item.Rating);
                                                        if (i <= temp)
                                                        {
                                                            <img src="/image/yellow-small-star.png" class="service-history-star-icon">

                                                        }
                                                        else
                                                        {
                                                            <img src="/image/grey-small-star.png" class="service-history-star-icon">
                                                        }

                                                    }
                                                    @{
                                                        var Rating = Convert.ToInt32(item.Rating);
                                                    }
                                                    @if (Rating > 3 && Rating <= 4)
                                                    {
                                                        <span>Very Good  </span>
                                                    }
                                                    else if (Rating > 4 && Rating <= 5)
                                                    {
                                                        <span>Excellent </span>
                                                    }
                                                    else if (Rating > 2 && Rating <= 3)
                                                    {
                                                        <span>Good </span>
                                                    }
                                                    else if (Rating > 1 && Rating <= 2)
                                                    {
                                                        <span>Poor </span>
                                                    }
                                                </div>
                                            </div>
                                            <hr class="mt-2" />
                                            <div class="col-md-12">
                                                <span class="font-bold"> Customer Comments:  </span>  @item.Comments
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>





        </div>
    </div>
</div>
@section Script{
    <style>
        a:hover {
            color: white !important;
        }
    </style>
    <link href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet">
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script>
        $("#selectRating").on('change', function () {
            $("#Form-submit").submit();
        });


        $(document).ready(function () {
            $("#selectRating").val("@ViewBag.selectRating");
        });

        $('#tbleMyRating').dataTable({
            "bFilter": false,
            "bInfo": false,
            'aoColumnDefs': [{
                'bSortable': false,
                'aTargets': [-1]  /* 1st one, start by the right */
            }],
            "order": [[0, "desc"]]
        });
    </script>
}

Helperland/Helperland/Views/ServiceProvider/NewServiceRquest.cshtml
@{
    Layout = "_Layout";
    ViewBag.Title = "New Service Request ";
}
@using Microsoft.AspNetCore.Http

@model List<Helperland.Models.ViewModel.ServiceProvider.NewServiceRequestViewModel>
<div class="container-fluid">
    <div class="row justify-content-center gray-bachgroud" style="margin-top: 100px; padding-top: 2rem; padding-bottom: 2rem;">
        <h1 class="text-center"> Welcome, @Context.Session.GetString("username") </h1>
    </div>
    <div class="row justify-content-center mt-2">
        <div class="col-md-2">
            <partial name="_ServiceProviderMenuPartialView" />
        </div>
        @{
            bool haspate = ViewBag.hasPat;
        }
        <div class="col-md-9">
            <div class="alert alert-success display-none" role="alert" id="alertSuccessMessage">
                Request Accepted Successfully.
            </div>
            <div class="alert alert-danger display-none" role="alert" id="alertErrorMessage">

            </div>
            <div class="row">
                <input type="hidden" value="@haspate" id="txtHiddenHaspate" />
                <div class="col-md-2">
                    <form method="get" asp-action="NewServiceRquest" asp-controller="ServiceProvider">
                        <input type="checkbox" name="hasPate" id="cbHaspate" /> <span class="font-bold">Pate at a Home </span>
                    </form>
                </div>
            </div>
            <div class="row p-3">
                <div class="col-md-12 table-responsive">
                    <table id="tbleNewServiceRequest" class="table table-outside-border table-hover">
                        <thead>
                            <tr class="gray-bachgroud">
                                <th>Service Id </th>
                                <th>Service Date </th>
                                <th>Customer Details </th>
                                <th>Payment</th>
                                <th> Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td onclick="OpenModel(@item.ServiceRequestID)"> @item.ServiceRequestID </td>
                                    <td class="flex" onclick="OpenModel(@item.ServiceRequestID)">
                                        <div><img src="/image/calendar2.png" asp-append-version="true"><b> @item.ServicestarDate</b> </div>
                                        8.:00 - 12:00
                                    </td>
                                    <td onclick="OpenModel(@item.ServiceRequestID)">

                                        <div class="d-flex">
                                            <div class="center"><img src="/image/layer-15.png"></div>
                                            <div>
                                                <span class="d-block"> @item.CustomerName </span>
                                                <span class="d-block"> @item.Addressline1 </span>
                                                <span class="d-block"> @item.Addressline2 </span>

                                            </div>

                                        </div>


                                    </td>
                                    <td class="active-font" onclick="OpenModel(@item.ServiceRequestID)">
                                        <div> <b> @item.Payment  €</b> </div>
                                    </td>
                                    <td>

                                        <button class="btn btn-success btn-sm font-white rounded-pill m-2" ata-bs-toggle="modal" data-bs-target="#ServiceDeatils" onclick="AcceptRequest(@item.ServiceRequestID)">Accept</button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Modal  Service Details -->
<div class="modal fade" id="ServiceDeatils" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered ">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Service Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12" id="ModelMainDiv">
                        <div>
                            <span id="ModelServiceDate" class="font-bold h5"></span> 8:00 - 13:00<br />
                            <span class="font-bold"> Duration </span><span id="ModelDuration"> </span> Hrs
                        </div>
                        <hr />
                        <div>
                            <span class="font-bold"> Service Id: </span><span id="ModelServiceRequestId"> </span>.<br />
                            <span class="font-bold"> Extras </span> <span id="ModelExtra"></span><br />
                            <span class="font-bold"> Net Amount: </span> <span id="ModelTotalCost" class="font-blue font-bold"></span> €<br />
                        </div>
                        <hr />
                        <div>
                            <span class="font-bold">Customer Name: </span><span id="ModelCustomerName"> </span><br />
                            <span class="font-bold"> Service Address :-  </span><span id="ModelServiceAddress"> </span>.

                        </div>
                        <hr />
                        <div>
                            <span class="font-bold"> Comments </span> <br /> <span id="ModelComments"> </span>
                        </div>
                        <hr />
                        <span> <img src="/image/not-included.png" id="ModelHasPatImage" /> I <span id="ModelHasPat">  don't </span>  have Pate at Home</span>
                        <hr />
                        <button class="btn btn-success font-white rounded-pill m-2" id="ModelbtnAccept" value="" onclick="AcceptRequest(this.value)">Accept </button>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@section Script{
    <style>
        a:hover {
            color: white !important;
        }
    </style>
    <link href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet">
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script>

        $(document).ready(function () {
            let cb = $("#txtHiddenHaspate").val();
            if (cb) {
                $('#cbHaspate').prop('checked', true);
            }
            else {
                $('#cbHaspate').prop('checked', false);
            }
            $('#cbHaspate').change(function () {
                $(this).closest('form').submit();
            });

           /* Apply Data Table*/
            $('#tbleNewServiceRequest').dataTable({
                "bFilter": false,
                "bInfo": false,
                'aoColumnDefs': [{
                    'bSortable': false,
                    'aTargets': [-1] /* 1st one, start by the right */
                }],
                "order": [[0, "desc"]]
            });

        });

           /*   Open Service Details Model on Click of Table Row*/
        function OpenModel(para) {
            $("#ServiceDeatils").modal('show');
            $("#ModelServiceRequestId").text(para);
            $("#ModelbtnAccept").val(para);
        $.ajax({
                  type: "POST",
            url: "@Url.Action("GetServiceRequestData")",
            data: { "ServiceReqestId": para },
                 success: function (responce) {
                     var obj = JSON.parse(responce);
                     $("#ModelDuration").text(obj.TotalHour);
                     $("#ModelServiceDate").text(obj.ServiceDate);
                     $("#ModelExtra").text(obj.Extra);
                     $("#ModelTotalCost").text(obj.TotalCost);
                     $("#ModelServiceAddress").text(obj.Address);
                     $("#ModelCustomerName").text(obj.CustomerName);
                     $("#ModelComments").text(obj.Comments);
                     if (obj.Haspet) {
                         $("#ModelHasPatImage").attr("src", "/image/included.png");
                         $("#ModelHasPat").hide();
                     } else {
                         $("#ModelHasPatImage").attr("src", "/image/not-included.png");
                         $("#ModelHasPat").show();
                     }


                 },
                 failure: function (response) {
                        alert("failure");
                 },
                 error: function (response) {
                        alert("Something went Worng");
                 }

              });
        }

        function AcceptRequest(para) {
            $("#ServiceDeatils").modal('hide');
            $(".loder-wrapper").fadeIn("fast");
             $.ajax({
                  type: "POST",
            url: "@Url.Action("AcceptServiceRequest")",
                 data: { "serviceRequeestId": para },
                 success: function (responce) {

                     if (responce == "true") {

                         $("#alertSuccessMessage").show().fadeOut(8000);
                         setTimeout(ReloadPage, 3000);

                     } else {
                         $("#alertErrorMessage").show().text(responce).fadeOut(10000);
                     }
                     $(".loder-wrapper").fadeOut("fast");

                 },
                 failure: function (response) {
                     alert("failure");
                     $(".loder-wrapper").fadeOut("fast");
                 },
                 error: function (response) {
                     alert("Something went Worng");
                     $(".loder-wrapper").fadeOut("fast");
                 }

              });
        }
        function ReloadPage() {
            location.reload();
        }

    </script>
}